dataset: 3Dlidc_idri
dataV: VI
verbose: true
base_fp: /nas-ctm01/homes/pfsousa/data
reader_fp: /nas-ctm01/homes/pfsousa/data/3Dlidc_idri
data_fp: /nas-ctm01/datasets/public/lidc_npy/3d/ct
data_format: npy
img_size: 128
img_channel: 1
num_slice: 0
slice_spacing: false
slice_bottom_margin: 5
slice_top_margin: 15
data_prep: true
h_flip: 50
val_split: 0
test_split: 0
batch_size: 1
num_fps: 4
shuffle: true
num_workers: 12
prefetch_factor: 1
