base_fp: /nas-ctm01/homes/pfsousa/data
batch_size: 1
dataV: V0
data_format: dicom
data_fp: /nas-ctm01/datasets/private/METABREST/T1W_Breast
data_prep: true
dataset: metabreast
h_flip: 50
img_channel: 1
img_size: 128
num_fps: 4
num_slice: 30
num_workers: 12
prefetch_factor: 1
reader_fp: /nas-ctm01/homes/pfsousa/data/metabreast
shuffle: true
slice_bottom_margin: 5
slice_spacing: false
slice_top_margin: 15
test_split: 0
val_split: 0
verbose: false
