dataset: luna25_nodule
dataV: VI
verbose: true
base_fp: X:/nas-ctm01/homes/pfsousa/data
reader_fp: X:/nas-ctm01/homes/pfsousa/data/luna25_nodule
data_fp: X:/nas-ctm01/datasets/public/medical_datasets/lung_ct_datasets/luna25_challenge/data_staging_area_II/protocol_1/data_npy_files/lung_nodule
data_format: npy
img_size: 32
img_channel: 1
num_slice: 0
slice_spacing: false
slice_bottom_margin: 5
slice_top_margin: 15
data_prep: true
h_flip: 50
val_split: 0
test_split: 0
batch_size: 1
num_fps: 4
shuffle: true
num_workers: 8
prefetch_factor: 1
